### ISSUE TITLE
Basic Order Management

### ISSUE THREAD

**Issue by sjs8760** [sjs8760/AgilePractice#10]
## Overview

For version 1.0 we want to be able to create a simple kiosk order that can read an image, choose the size, and print the picture. 
We will use this as a base to get feed back and build up the system features. 

### Motivation / User Needs:

Our main stakeholders are big super markets with many customers who would like to print pictures that they take from their cameras. 
Most of their customers carry a usb memory stick with their pictures so they would like to be able to print from USB.  

### Use Cases:

A kiosk will be placed in the super market where customers can come and use it. 
Customers will use the kiosk one at a time to print 1 image orders. 

## Main Requirements

- [ ] Create an order
- [ ] Add an image to the order
- [ ] Remove an image from the order
- [ ] Cancel the order
- [ ] Print the order

### Design Requirements & System Limitations

For version 1.0 order will only be made from the local kiosk UI.
Images will only be selectable from a usb device.
The image types will be limited to jpg only.
No customer information is necessary for v1.0. The order is "one and done"

## Team Notes / Future Tasks

The hardware and firmware is already prepared for us. 
All we need to do is complete the software.
