### ISSUE TITLE
Create an Order 

### ISSUE THREAD

**Issue by sjs8760** [sjs8760/AgilePractice#11]
## Overview

This will describe how an order is created and what information is necessary. 

### Motivation / User Needs:

It's important to have a simple UI for users to quickly create their orders. 

### Use Case:

A user will touch the screen to activate the terminal and then a "Create Order" button will appear.
When the "Create Order" button is pressed the user will be prompted to input their name and contact information.
Then the user will press the "Continue" button to create their order. 

From here the user will be able to add items, edit their order, checkout etc...

## Main Requirements

- [x] There must be a "Create Order" button for the user to interact with
- [x] The system should have a section to enter the user's name and contact information
- [x] The system should have a "Complete" button to create the order.
