### ISSUE TITLE
Add an item to an Order

### ISSUE THREAD

**Issue by sjs8760** [sjs8760/AgilePractice#12]
## Overview

After an order has been created we need to add the items to the order. 
For v1.0 we will simply support jpg images that will be read from a usb drive.

### Motivation / User Needs:

Many people who take pictures on their phone and camera save their photos on a usb drive. 
They want to be able to quickly connect their usb drive and choose a photo to print. 

### Use Cases:

When prompted, the user should input their usb device. 
When a usb device has been detected by the system, it will automatically display a list of all of the jpg files found.
When the user selects an image the "Add to Order" button will highlight and, when pressed, add the image to the order. 

## Main Requirements

- [ ] The system should be able to read a USB drive
- [ ] The system must display a list of image files
- [ ] The user must be able to select a single file
- [ ] The user must be able to add a selected item via an "Add to Order" button

### Design Requirements & System Limitations

The system should search all of the folders for images.
The system only needs to display the images as a list of text (no img previews necessary)
The file size and details do not need to be displayed.
